### ISSUE TITLE
How to emulate a joystick in linux with evdev?

### ISSUE THREAD

**Issue by saminhasan** [dperelman/gamepad-util#3]
Sir i would be really grateful,if you could answer this question -https://stackoverflow.com/questions/63201214/how-to-emulate-a-xbox-360-controller-in-ubuntu-16-04

**Comment by dperelman** [comment]
https://github.com/dperelman/wii-u-gc-adapter/tree/feature/mimic-xpad might be a helpful starting place. It's just some minor modifications on top of [ToadKing/wii-u-gc-adapter](https://github.com/ToadKing/wii-u-gc-adapter) to emulate an XBox 360 controller based on inputs from a GameCube controller plugged in via the USB Wii U adapter for them, but it should show the example of how to emulate an XBox 360 controller and you should be able to modify it to get the inputs from wherever.

Note that `uinput` is the relevant library, not `evdev`. And it's a kernel module, so I wouldn't be surprised if it's not supported on WSL (EDIT2: [WSL does not support `uinput`](https://github.com/Microsoft/WSL/issues/3997)). (EDIT: Ah, it looks like Python's `evdev` library includes support for `uinput`.)

**Comment by saminhasan** [comment]
Sir solved my problem in a slightly different manner. Solution can be found in this [repo.](https://github.com/Saminhasan5220)

Thank you for time and resources.
